spring:
  profiles:
    active: mysql
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      username: ${REDIS_USERNAME:spring_app_user}
      password: ${REDIS_PASSWORD:MySecretPassword123}

# uncomment below logging details so that you can see each step of the debug process while the application is getting executed

# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG


# our verification token expiry date for registering a new user
verification:
  Token:
    expiry:
      seconds: 600


# user's frontend application url . when user goes to this frontend url it is going to call our backend to verify the user
frontend:
  applicationUrl:
    user:
      api: http://localhost:5000
# data related to the public key private key and the expiry time of the jwt in seconds from when the jwt is first issued
jwt:
  public:
    key: classpath:publicKey.pem
  private:
    key: classpath:privateKey.pem
  token:
    expiry: 
      seconds: 60000


#our custom mail configuration
mail:
  config1:
    host: smtp-mail.outlook.com
    port: 587
    username: irisnote1@outlook.com
    password: gwfewxteraivvfrq
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
  config2:
    host: smtp-mail.outlook.com
    port: 587
    username: not-app1@hotmail.com
    password: zkxoydihrptbnmwt
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
